if(EXISTS "/Users/danielsilva/Documents/Docker/docker-gcc/hello_test[1]_tests.cmake")
  include("/Users/danielsilva/Documents/Docker/docker-gcc/hello_test[1]_tests.cmake")
else()
  add_test(hello_test_NOT_BUILT hello_test_NOT_BUILT)
endif()
