if(EXISTS "/Users/danielsilva/Documents/Docker/docker-gcc/test[1]_tests.cmake")
  include("/Users/danielsilva/Documents/Docker/docker-gcc/test[1]_tests.cmake")
else()
  add_test(test_NOT_BUILT test_NOT_BUILT)
endif()
